Tushar Sharma

B B3 41

ML Practical-4

In [50]:
import pandas as pd
df=pd.read_csv("car_evaluation.csv")

In [52]:
df.head(30-24)

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc
5  vhigh   vhigh  2   2    big   low  unacc

In [54]:
df.tail(20)

     vhigh vhigh.1      2   2.1  small   low  unacc
1707   low     low  5more     2    big   med  unacc
1708   low     low  5more     2    big  high  unacc
1709   low     low  5more     4  small   low  unacc
1710   low     low  5more     4  small   med    acc
1711   low     low  5more     4  small  high   good
1712   low     low  5more     4    med   low  unacc
1713   low     low  5more     4    med   med   good
1714   low     low  5more     4    med  high  vgood
1715   low     low  5more     4    big   low  unacc
1716   low     low  5more     4    big   med   good
1717   low     low  5more     4    big  high  vgood
1718   low     low  5more  more  small   low  unacc
1719   low     low  5more  more  small   med    acc
1720   low     low  5more  more  small  high   good
1721   low     low  5more  more    med   low  unacc
1722   low     low  5more  more    med   med   good
1723   low     low  5more  more    med  high  vgood
1724   low     low  5more  more    big   low  unacc
1725   low     low  5more  more    big   med   good
1726   low     low  5more  more    big  high  vgood

In [56]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [58]:
import numpy as np

def find_s(X, y):
    hypothesis = None
    print("Initial Hypothesis:", hypothesis)
    
    for i in range(len(X)):
        if y[i] != "unacceptable":
            if hypothesis is None:
                hypothesis = X[i].copy()
            else:
                for j in range(len(hypothesis)):
                    if hypothesis[j] != X[i][j]:
                        hypothesis[j] = "?"
            print(f"\nAfter Training Example {i + 1}")
            print(hypothesis)
            
    return hypothesis

final_hypothesis = find_s(X, y)
print("\nFinal Hypothesis:", final_hypothesis)

Initial Hypothesis: None

After Training Example 1
['vhigh' 'vhigh' '2' '2' 'small' 'med']

After Training Example 2
['vhigh' 'vhigh' '2' '2' 'small' '?']

After Training Example 3
['vhigh' 'vhigh' '2' '2' '?' '?']

After Training Example 4
['vhigh' 'vhigh' '2' '2' '?' '?']

After Training Example 5
['vhigh' 'vhigh' '2' '2' '?' '?']

After Training Example 6
['vhigh' 'vhigh' '2' '2' '?' '?']

After Training Example 7
['vhigh' 'vhigh' '2' '2' '?' '?']

After Training Example 8
['vhigh' 'vhigh' '2' '2' '?' '?']

After Training Example 9
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 10
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 11
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 12
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 13
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 14
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 15
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 16
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 17
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 18
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 19
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 20
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 21
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 22
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 23
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 24
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 25
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 26
['vhigh' 'vhigh' '2' '?' '?' '?']

After Training Example 27
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 28
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 29
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 30
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 31
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 32
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 33
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 34
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 35
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 36
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 37
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 38
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 39
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 40
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 41
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 42
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 43
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 44
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 45
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 46
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 47
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 48
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 49
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 50
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 51
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 52
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 53
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 54
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 55
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 56
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 57
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 58
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 59
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 60
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 61
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 62
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 63
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 64
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 65
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 66
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 67
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 68
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 69
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 70
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 71
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 72
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 73
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 74
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 75
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 76
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 77
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 78
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 79
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 80
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 81
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 82
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 83
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 84
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 85
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 86
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 87
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 88
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 89
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 90
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 91
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 92
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 93
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 94
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 95
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 96
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 97
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 98
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 99
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 100
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 101
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 102
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 103
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 104
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 105
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 106
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 107
['vhigh' 'vhigh' '?' '?' '?' '?']

After Training Example 108
['vhigh' '?' '?' '?' '?' '?']

After Training Example 109
['vhigh' '?' '?' '?' '?' '?']

After Training Example 110
['vhigh' '?' '?' '?' '?' '?']

After Training Example 111
['vhigh' '?' '?' '?' '?' '?']

After Training Example 112
['vhigh' '?' '?' '?' '?' '?']

After Training Example 113
['vhigh' '?' '?' '?' '?' '?']

After Training Example 114
['vhigh' '?' '?' '?' '?' '?']

After Training Example 115
['vhigh' '?' '?' '?' '?' '?']

After Training Example 116
['vhigh' '?' '?' '?' '?' '?']

After Training Example 117
['vhigh' '?' '?' '?' '?' '?']

After Training Example 118
['vhigh' '?' '?' '?' '?' '?']

After Training Example 119
['vhigh' '?' '?' '?' '?' '?']

After Training Example 120
['vhigh' '?' '?' '?' '?' '?']

After Training Example 121
['vhigh' '?' '?' '?' '?' '?']

After Training Example 122
['vhigh' '?' '?' '?' '?' '?']

After Training Example 123
['vhigh' '?' '?' '?' '?' '?']

After Training Example 124
['vhigh' '?' '?' '?' '?' '?']

After Training Example 125
['vhigh' '?' '?' '?' '?' '?']

After Training Example 126
['vhigh' '?' '?' '?' '?' '?']

After Training Example 127
['vhigh' '?' '?' '?' '?' '?']

After Training Example 128
['vhigh' '?' '?' '?' '?' '?']

After Training Example 129
['vhigh' '?' '?' '?' '?' '?']

After Training Example 130
['vhigh' '?' '?' '?' '?' '?']

After Training Example 131
['vhigh' '?' '?' '?' '?' '?']

After Training Example 132
['vhigh' '?' '?' '?' '?' '?']

After Training Example 133
['vhigh' '?' '?' '?' '?' '?']

After Training Example 134
['vhigh' '?' '?' '?' '?' '?']

After Training Example 135
['vhigh' '?' '?' '?' '?' '?']

After Training Example 136
['vhigh' '?' '?' '?' '?' '?']

After Training Example 137
['vhigh' '?' '?' '?' '?' '?']

After Training Example 138
['vhigh' '?' '?' '?' '?' '?']

After Training Example 139
['vhigh' '?' '?' '?' '?' '?']

After Training Example 140
['vhigh' '?' '?' '?' '?' '?']

After Training Example 141
['vhigh' '?' '?' '?' '?' '?']

After Training Example 142
['vhigh' '?' '?' '?' '?' '?']

After Training Example 143
['vhigh' '?' '?' '?' '?' '?']

After Training Example 144
['vhigh' '?' '?' '?' '?' '?']

After Training Example 145
['vhigh' '?' '?' '?' '?' '?']

After Training Example 146
['vhigh' '?' '?' '?' '?' '?']

After Training Example 147
['vhigh' '?' '?' '?' '?' '?']

After Training Example 148
['vhigh' '?' '?' '?' '?' '?']

After Training Example 149
['vhigh' '?' '?' '?' '?' '?']

After Training Example 150
['vhigh' '?' '?' '?' '?' '?']

After Training Example 151
['vhigh' '?' '?' '?' '?' '?']

After Training Example 152
['vhigh' '?' '?' '?' '?' '?']

After Training Example 153
['vhigh' '?' '?' '?' '?' '?']

After Training Example 154
['vhigh' '?' '?' '?' '?' '?']

After Training Example 155
['vhigh' '?' '?' '?' '?' '?']

After Training Example 156
['vhigh' '?' '?' '?' '?' '?']

After Training Example 157
['vhigh' '?' '?' '?' '?' '?']

After Training Example 158
['vhigh' '?' '?' '?' '?' '?']

After Training Example 159
['vhigh' '?' '?' '?' '?' '?']

After Training Example 160
['vhigh' '?' '?' '?' '?' '?']

After Training Example 161
['vhigh' '?' '?' '?' '?' '?']

After Training Example 162
['vhigh' '?' '?' '?' '?' '?']

After Training Example 163
['vhigh' '?' '?' '?' '?' '?']

After Training Example 164
['vhigh' '?' '?' '?' '?' '?']

After Training Example 165
['vhigh' '?' '?' '?' '?' '?']

After Training Example 166
['vhigh' '?' '?' '?' '?' '?']

After Training Example 167
['vhigh' '?' '?' '?' '?' '?']

After Training Example 168
['vhigh' '?' '?' '?' '?' '?']

After Training Example 169
['vhigh' '?' '?' '?' '?' '?']

After Training Example 170
['vhigh' '?' '?' '?' '?' '?']

After Training Example 171
['vhigh' '?' '?' '?' '?' '?']

After Training Example 172
['vhigh' '?' '?' '?' '?' '?']

After Training Example 173
['vhigh' '?' '?' '?' '?' '?']

After Training Example 174
['vhigh' '?' '?' '?' '?' '?']

After Training Example 175
['vhigh' '?' '?' '?' '?' '?']

After Training Example 176
['vhigh' '?' '?' '?' '?' '?']

After Training Example 177
['vhigh' '?' '?' '?' '?' '?']

After Training Example 178
['vhigh' '?' '?' '?' '?' '?']

After Training Example 179
['vhigh' '?' '?' '?' '?' '?']

After Training Example 180
['vhigh' '?' '?' '?' '?' '?']

After Training Example 181
['vhigh' '?' '?' '?' '?' '?']

After Training Example 182
['vhigh' '?' '?' '?' '?' '?']

After Training Example 183
['vhigh' '?' '?' '?' '?' '?']

After Training Example 184
['vhigh' '?' '?' '?' '?' '?']

After Training Example 185
['vhigh' '?' '?' '?' '?' '?']

After Training Example 186
['vhigh' '?' '?' '?' '?' '?']

After Training Example 187
['vhigh' '?' '?' '?' '?' '?']

After Training Example 188
['vhigh' '?' '?' '?' '?' '?']

After Training Example 189
['vhigh' '?' '?' '?' '?' '?']

After Training Example 190
['vhigh' '?' '?' '?' '?' '?']

After Training Example 191
['vhigh' '?' '?' '?' '?' '?']

After Training Example 192
['vhigh' '?' '?' '?' '?' '?']

After Training Example 193
['vhigh' '?' '?' '?' '?' '?']

After Training Example 194
['vhigh' '?' '?' '?' '?' '?']

After Training Example 195
['vhigh' '?' '?' '?' '?' '?']

After Training Example 196
['vhigh' '?' '?' '?' '?' '?']

After Training Example 197
['vhigh' '?' '?' '?' '?' '?']

After Training Example 198
['vhigh' '?' '?' '?' '?' '?']

After Training Example 199
['vhigh' '?' '?' '?' '?' '?']

After Training Example 200
['vhigh' '?' '?' '?' '?' '?']

After Training Example 201
['vhigh' '?' '?' '?' '?' '?']

After Training Example 202
['vhigh' '?' '?' '?' '?' '?']

After Training Example 203
['vhigh' '?' '?' '?' '?' '?']

After Training Example 204
['vhigh' '?' '?' '?' '?' '?']

After Training Example 205
['vhigh' '?' '?' '?' '?' '?']

After Training Example 206
['vhigh' '?' '?' '?' '?' '?']

After Training Example 207
['vhigh' '?' '?' '?' '?' '?']

After Training Example 208
['vhigh' '?' '?' '?' '?' '?']

After Training Example 209
['vhigh' '?' '?' '?' '?' '?']

After Training Example 210
['vhigh' '?' '?' '?' '?' '?']

After Training Example 211
['vhigh' '?' '?' '?' '?' '?']

After Training Example 212
['vhigh' '?' '?' '?' '?' '?']

After Training Example 213
['vhigh' '?' '?' '?' '?' '?']

After Training Example 214
['vhigh' '?' '?' '?' '?' '?']

After Training Example 215
['vhigh' '?' '?' '?' '?' '?']

After Training Example 216
['vhigh' '?' '?' '?' '?' '?']

After Training Example 217
['vhigh' '?' '?' '?' '?' '?']

After Training Example 218
['vhigh' '?' '?' '?' '?' '?']

After Training Example 219
['vhigh' '?' '?' '?' '?' '?']

After Training Example 220
['vhigh' '?' '?' '?' '?' '?']

After Training Example 221
['vhigh' '?' '?' '?' '?' '?']

After Training Example 222
['vhigh' '?' '?' '?' '?' '?']

After Training Example 223
['vhigh' '?' '?' '?' '?' '?']

After Training Example 224
['vhigh' '?' '?' '?' '?' '?']

After Training Example 225
['vhigh' '?' '?' '?' '?' '?']

After Training Example 226
['vhigh' '?' '?' '?' '?' '?']

After Training Example 227
['vhigh' '?' '?' '?' '?' '?']

After Training Example 228
['vhigh' '?' '?' '?' '?' '?']

After Training Example 229
['vhigh' '?' '?' '?' '?' '?']

After Training Example 230
['vhigh' '?' '?' '?' '?' '?']

After Training Example 231
['vhigh' '?' '?' '?' '?' '?']

After Training Example 232
['vhigh' '?' '?' '?' '?' '?']

After Training Example 233
['vhigh' '?' '?' '?' '?' '?']

After Training Example 234
['vhigh' '?' '?' '?' '?' '?']

After Training Example 235
['vhigh' '?' '?' '?' '?' '?']

After Training Example 236
['vhigh' '?' '?' '?' '?' '?']

After Training Example 237
['vhigh' '?' '?' '?' '?' '?']

After Training Example 238
['vhigh' '?' '?' '?' '?' '?']

After Training Example 239
['vhigh' '?' '?' '?' '?' '?']

After Training Example 240
['vhigh' '?' '?' '?' '?' '?']

After Training Example 241
['vhigh' '?' '?' '?' '?' '?']

After Training Example 242
['vhigh' '?' '?' '?' '?' '?']

After Training Example 243
['vhigh' '?' '?' '?' '?' '?']

After Training Example 244
['vhigh' '?' '?' '?' '?' '?']

After Training Example 245
['vhigh' '?' '?' '?' '?' '?']

After Training Example 246
['vhigh' '?' '?' '?' '?' '?']

After Training Example 247
['vhigh' '?' '?' '?' '?' '?']

After Training Example 248
['vhigh' '?' '?' '?' '?' '?']

After Training Example 249
['vhigh' '?' '?' '?' '?' '?']

After Training Example 250
['vhigh' '?' '?' '?' '?' '?']

After Training Example 251
['vhigh' '?' '?' '?' '?' '?']

After Training Example 252
['vhigh' '?' '?' '?' '?' '?']

After Training Example 253
['vhigh' '?' '?' '?' '?' '?']

After Training Example 254
['vhigh' '?' '?' '?' '?' '?']

After Training Example 255
['vhigh' '?' '?' '?' '?' '?']

After Training Example 256
['vhigh' '?' '?' '?' '?' '?']

After Training Example 257
['vhigh' '?' '?' '?' '?' '?']

After Training Example 258
['vhigh' '?' '?' '?' '?' '?']

After Training Example 259
['vhigh' '?' '?' '?' '?' '?']

After Training Example 260
['vhigh' '?' '?' '?' '?' '?']

After Training Example 261
['vhigh' '?' '?' '?' '?' '?']

After Training Example 262
['vhigh' '?' '?' '?' '?' '?']

After Training Example 263
['vhigh' '?' '?' '?' '?' '?']

After Training Example 264
['vhigh' '?' '?' '?' '?' '?']

After Training Example 265
['vhigh' '?' '?' '?' '?' '?']

After Training Example 266
['vhigh' '?' '?' '?' '?' '?']

After Training Example 267
['vhigh' '?' '?' '?' '?' '?']

After Training Example 268
['vhigh' '?' '?' '?' '?' '?']

After Training Example 269
['vhigh' '?' '?' '?' '?' '?']

After Training Example 270
['vhigh' '?' '?' '?' '?' '?']

After Training Example 271
['vhigh' '?' '?' '?' '?' '?']

After Training Example 272
['vhigh' '?' '?' '?' '?' '?']

After Training Example 273
['vhigh' '?' '?' '?' '?' '?']

After Training Example 274
['vhigh' '?' '?' '?' '?' '?']

After Training Example 275
['vhigh' '?' '?' '?' '?' '?']

After Training Example 276
['vhigh' '?' '?' '?' '?' '?']

After Training Example 277
['vhigh' '?' '?' '?' '?' '?']

After Training Example 278
['vhigh' '?' '?' '?' '?' '?']

After Training Example 279
['vhigh' '?' '?' '?' '?' '?']

After Training Example 280
['vhigh' '?' '?' '?' '?' '?']

After Training Example 281
['vhigh' '?' '?' '?' '?' '?']

After Training Example 282
['vhigh' '?' '?' '?' '?' '?']

After Training Example 283
['vhigh' '?' '?' '?' '?' '?']

After Training Example 284
['vhigh' '?' '?' '?' '?' '?']

After Training Example 285
['vhigh' '?' '?' '?' '?' '?']

After Training Example 286
['vhigh' '?' '?' '?' '?' '?']

After Training Example 287
['vhigh' '?' '?' '?' '?' '?']

After Training Example 288
['vhigh' '?' '?' '?' '?' '?']

After Training Example 289
['vhigh' '?' '?' '?' '?' '?']

After Training Example 290
['vhigh' '?' '?' '?' '?' '?']

After Training Example 291
['vhigh' '?' '?' '?' '?' '?']

After Training Example 292
['vhigh' '?' '?' '?' '?' '?']

After Training Example 293
['vhigh' '?' '?' '?' '?' '?']

After Training Example 294
['vhigh' '?' '?' '?' '?' '?']

After Training Example 295
['vhigh' '?' '?' '?' '?' '?']

After Training Example 296
['vhigh' '?' '?' '?' '?' '?']

After Training Example 297
['vhigh' '?' '?' '?' '?' '?']

After Training Example 298
['vhigh' '?' '?' '?' '?' '?']

After Training Example 299
['vhigh' '?' '?' '?' '?' '?']

After Training Example 300
['vhigh' '?' '?' '?' '?' '?']

After Training Example 301
['vhigh' '?' '?' '?' '?' '?']

After Training Example 302
['vhigh' '?' '?' '?' '?' '?']

After Training Example 303
['vhigh' '?' '?' '?' '?' '?']

After Training Example 304
['vhigh' '?' '?' '?' '?' '?']

After Training Example 305
['vhigh' '?' '?' '?' '?' '?']

After Training Example 306
['vhigh' '?' '?' '?' '?' '?']

After Training Example 307
['vhigh' '?' '?' '?' '?' '?']

After Training Example 308
['vhigh' '?' '?' '?' '?' '?']

After Training Example 309
['vhigh' '?' '?' '?' '?' '?']

After Training Example 310
['vhigh' '?' '?' '?' '?' '?']

After Training Example 311
['vhigh' '?' '?' '?' '?' '?']

After Training Example 312
['vhigh' '?' '?' '?' '?' '?']

After Training Example 313
['vhigh' '?' '?' '?' '?' '?']

After Training Example 314
['vhigh' '?' '?' '?' '?' '?']

After Training Example 315
['vhigh' '?' '?' '?' '?' '?']

After Training Example 316
['vhigh' '?' '?' '?' '?' '?']

After Training Example 317
['vhigh' '?' '?' '?' '?' '?']

After Training Example 318
['vhigh' '?' '?' '?' '?' '?']

After Training Example 319
['vhigh' '?' '?' '?' '?' '?']

After Training Example 320
['vhigh' '?' '?' '?' '?' '?']

After Training Example 321
['vhigh' '?' '?' '?' '?' '?']

After Training Example 322
['vhigh' '?' '?' '?' '?' '?']

After Training Example 323
['vhigh' '?' '?' '?' '?' '?']

After Training Example 324
['vhigh' '?' '?' '?' '?' '?']

After Training Example 325
['vhigh' '?' '?' '?' '?' '?']

After Training Example 326
['vhigh' '?' '?' '?' '?' '?']

After Training Example 327
['vhigh' '?' '?' '?' '?' '?']

After Training Example 328
['vhigh' '?' '?' '?' '?' '?']

After Training Example 329
['vhigh' '?' '?' '?' '?' '?']

After Training Example 330
['vhigh' '?' '?' '?' '?' '?']

After Training Example 331
['vhigh' '?' '?' '?' '?' '?']

After Training Example 332
['vhigh' '?' '?' '?' '?' '?']

After Training Example 333
['vhigh' '?' '?' '?' '?' '?']

After Training Example 334
['vhigh' '?' '?' '?' '?' '?']

After Training Example 335
['vhigh' '?' '?' '?' '?' '?']

After Training Example 336
['vhigh' '?' '?' '?' '?' '?']

After Training Example 337
['vhigh' '?' '?' '?' '?' '?']

After Training Example 338
['vhigh' '?' '?' '?' '?' '?']

After Training Example 339

Candidate Elimination Algorithm

In [61]:
import numpy as np

def candidate_elimination(concepts, target):
    specific_h = None
    for i in range(len(target)):
        if target[i] != "unacceptable":
            specific_h = concepts[i].copy()
            break            
    general_h = [["?" for _ in range(len(specific_h))]]   
    print("Initial S:", specific_h)
    print("Initial G:", general_h)    
    for i, h in enumerate(concepts):
        if target[i] != "unacceptable":
            general_h = [g for g in general_h if all(g[k] == '?' or g[k] == h[k] for k in range(len(specific_h)))]
            for x in range(len(specific_h)):
                if h[x] != specific_h[x]:
                    specific_h[x] = '?'
        else: 
            new_G = []
            for g in general_h:
                if all(g[k] == '?' or g[k] == h[k] for k in range(len(specific_h))):
                    for x in range(len(specific_h)):
                        if h[x] != specific_h[x]:
                            g_new = g.copy()
                            g_new[x] = specific_h[x]
                            if g_new not in new_G:
                                new_G.append(g_new)
                else:
                    new_G.append(g)
            general_h = new_G
        print(f"\nExample {i + 1}")
        print("S =", specific_h)
        print("G =", general_h)      
    return specific_h, general_h
S, G = candidate_elimination(X, y)
print("\nFinal Specific Boundary:")
print(S)
print("\nFinal General Boundary:")
for g in G:
    print(g)

Initial S: ['vhigh' 'vhigh' '2' '2' 'small' 'med']
Initial G: [['?', '?', '?', '?', '?', '?']]

Example 1
S = ['vhigh' 'vhigh' '2' '2' 'small' 'med']
G = [['?', '?', '?', '?', '?', '?']]

Example 2
S = ['vhigh' 'vhigh' '2' '2' 'small' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 3
S = ['vhigh' 'vhigh' '2' '2' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 4
S = ['vhigh' 'vhigh' '2' '2' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 5
S = ['vhigh' 'vhigh' '2' '2' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 6
S = ['vhigh' 'vhigh' '2' '2' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 7
S = ['vhigh' 'vhigh' '2' '2' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 8
S = ['vhigh' 'vhigh' '2' '2' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 9
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 10
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 11
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 12
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 13
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 14
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 15
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 16
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 17
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 18
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 19
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 20
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 21
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 22
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 23
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 24
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 25
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 26
S = ['vhigh' 'vhigh' '2' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 27
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 28
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 29
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 30
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 31
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 32
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 33
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 34
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 35
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 36
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 37
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 38
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 39
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 40
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 41
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 42
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 43
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 44
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 45
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 46
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 47
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 48
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 49
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 50
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 51
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 52
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 53
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 54
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 55
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 56
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 57
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 58
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 59
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 60
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 61
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 62
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 63
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 64
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 65
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 66
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 67
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 68
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 69
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 70
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 71
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 72
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 73
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 74
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 75
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 76
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 77
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 78
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 79
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 80
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 81
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 82
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 83
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 84
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 85
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 86
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 87
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 88
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 89
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 90
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 91
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 92
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 93
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 94
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 95
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 96
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 97
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 98
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 99
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 100
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 101
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 102
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 103
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 104
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 105
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 106
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 107
S = ['vhigh' 'vhigh' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 108
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 109
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 110
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 111
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 112
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 113
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 114
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 115
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 116
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 117
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 118
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 119
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 120
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 121
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 122
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 123
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 124
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 125
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 126
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 127
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 128
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 129
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 130
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 131
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 132
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 133
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 134
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 135
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 136
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 137
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 138
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 139
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 140
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 141
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 142
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 143
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 144
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 145
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 146
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 147
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 148
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 149
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 150
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 151
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 152
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 153
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 154
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 155
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 156
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 157
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 158
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 159
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 160
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 161
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 162
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 163
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 164
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 165
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 166
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 167
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 168
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 169
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 170
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 171
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 172
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 173
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 174
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 175
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 176
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 177
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 178
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 179
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 180
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 181
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 182
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 183
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 184
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 185
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 186
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 187
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 188
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 189
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 190
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 191
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 192
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 193
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 194
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 195
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 196
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 197
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 198
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 199
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 200
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 201
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 202
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 203
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 204
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 205
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 206
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 207
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 208
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 209
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 210
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 211
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 212
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 213
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 214
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 215
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 216
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 217
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 218
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 219
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 220
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 221
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 222
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 223
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 224
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 225
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 226
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 227
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 228
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 229
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 230
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 231
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 232
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]

Example 233
S = ['vhigh' '?' '?' '?' '?' '?']
G = [['?', '?', '?', '?', '?', '?']]
